export const theme = {
    colors: {
        page: "var(--color-page)",
        surface: "var(--color-surface)",
        surfaceSoft: "var(--color-surface-soft)",
        border: "var(--color-border)",
        borderMuted: "var(--color-border-muted)",
        borderLight: "var(--color-border-light)",
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primary-dark)",
        accent: "var(--color-accent)",
        accentDark: "var(--color-accent-dark)",
        accentSoft: "var(--color-accent-soft)",
        info: "var(--color-info)",
        infoDark: "var(--color-info-dark)",
        infoLight: "var(--color-info-light)",
        muted: "var(--color-muted)",
        mutedLight: "var(--color-muted-light)",
        mutedLighter: "var(--color-muted-lighter)",
        textPrimary: "var(--color-text-primary)",
        textSecondary: "var(--color-text-secondary)",
        textMuted: "var(--color-text-muted)",
        textFooter: "var(--color-text-footer)",
        banner: "var(--color-banner)",
        sidebar: "var(--color-sidebar)",
        highlight: "var(--color-highlight)",
        success: "var(--color-success)",
        warningSoft: "var(--color-warning-soft)",
        card: "var(--color-card)",
    },
};
